application:
  port: 8080
  channelSecret: "inputYourChannelSecret"
  channelAccessToken: "inputYourChannelAccessToken"
  dbURI: "mongodb://localhost:27017"
  database: "line_robot"
  dbCollection: "messages"